-- 建立兩個 table
-- 帳號表格
CREATE TABLE ACCOUNT(ID INT IDENTITY PRIMARY KEY, NAME VARCHAR(200), AMOUNT DECIMAL(20,2));
-- 記錄表格
CREATE TABLE LOG(ID INT IDENTITY PRIMARY KEY, NAME VARCHAR(200), MESSAGE VARCHAR(800), LOGTIME TIMESTAMP);